### ISSUE TITLE
IPC::System::Simple missing from non-standard module list

### ISSUE THREAD

**Issue by bsdzilla** [Ovid/git-workflow#3]
Docs should add this module..

**Comment by Ovid** [comment]
hi @bsdzilla. I just double-checked (because I'm forgetful), but I don't see any place in my code where that's used. Could you explain?

**Comment by bsdzilla** [comment]
./git-hub
IPC::System::Simple required for Fatalised/autodying system() at ./git-hub line 12.
        main::BEGIN() called at ./git-hub line 12
        eval {...} called at ./git-hub line 12
BEGIN failed--compilation aborted at ./git-hub line 12.

It does not get pulled in via the other dependencies you mentioned..

**Comment by Ovid** [comment]
Thank you. It's now added to the `README.md`.
